FROM    python:3.6.13-slim-buster

#WORKDIR /root
COPY . /root/
RUN apt-get update && apt-get install -y cmake wget llvm aria2 unzip
RUN apt-get install -y libxrender-dev && \
    apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev

WORKDIR /root

RUN cd src/imagecluster/ && \
    pip3 install -e .
RUN pip3 install -r requirement.txt
RUN gdown --id 12oyXwsQ3Z0_oRTIQMdzVjCumN7hXaCVH && \
    unzip models.zip
RUN apt-get update && apt-get install -y ffmpeg libgl1-mesa-glx libprotoc-dev 
RUN python3 app.py
